services:
  web:
    build:
      context: .
      target: web
    env_file:
      - ./web/.env
    ports:
      - "9901:9901"

  admin:
    build:
      context: .
      target: admin
    env_file:
      - ./admin/.env
    ports:
      - "9902:9902"
