services:
  web:
    build:
      context: .
      target: web
    env_file:
      - ./web/.env
    ports:
      - "9901:9901"

  admin:
    build:
      context: .
      target: admin
    env_file:
      - ./admin/.env
    environment:
      NODE_OPTIONS: --dns-result-order=ipv4first
    ports:
      - "9902:9902"
