services:
  web:
    image: ${VISION_WEB_IMAGE}
    env_file:
      - ./web.env
    ports:
      - "9901:9901"
    restart: always
    networks:
      - vision-net

  admin:
    image: ${VISION_ADMIN_IMAGE}
    env_file:
      - ./admin.env
    ports:
      - "9902:9902"
    restart: always
    networks:
      - vision-net

networks:
  vision-net:
    driver: bridge
