project_id = "vision"

[storage]
enabled = true

[storage.buckets.images]
public = true

[functions.generate-image]
verify_jwt = false

[functions.check-email]
verify_jwt = false

[functions.admin-users]
verify_jwt = false
